let brawlhalla = [
    'Bödvar', 
    'Cassidy',
    'Orion',
    'Lord Vraxx',
    'Gnash',
    'Queen Nai',
    'Hattori',
    'SirRoland',
    'Scarlet',
    'Thatch',
    'Ada',
    'Sentinel',
    'Lucien',
    'Teros',
    'Brynn',
    'Asuri',
    'Barraza',
    'Ember',
    'Azoth',
    'Koji',
    'Ulgrim',
    'Diana',
    'Jhala',
    'Kor',
    'Wu Shang',
    'Val',
    'Ragnir',
    'Cross',
    'Mirage',
    'Nix',
    'Mordex',
    'Yumiko',
    'Artemis',
    'Caspian',
    'Sidra',
    'Xull',
    'Kaya',
    'Isaiah',
    'Jiro',
    'Lin Fei',
    'Zariel',
    'Rayman',
    'Dusk',
    'Fait',
    'Thor',
    'Petra',
    'Vector',
    'Volkov',
    'Onyx',
    'Jaeyun',
    'Mako',
    'Magyar',
    'Reno',
    'Munin',
    'Arcadia'
]

    console.log(brawlhalla[Math.floor(Math.random() * brawlhalla.length)]);
